define: &eps 1.0e-08
device: cuda:0
h: 1.25
DEBUG: False
peak_threshold: 0.02
max_peaks: 5
relative_threshold: 0.1
min_separation_angle: 10
n_neighbor: 6
eps: *eps
#normal_dis, random
init_type: normal_dis
loss_params:
  lambda1: 1
  lambda2: 1
  lambda3: 1
  lambda4: 0.5
  lambda5: 0.5
  lambda6: 1
  entropy_param: 1.0e-6
  js_param: 1.0e-6
  peak_choose_type: soft
  gumbel_tau: 0.1
  eps: *eps
  entropy_threshold: 0
reg_lambda: 0.001
lr: 0.1
img_log_params:
  img_roi:
    - 19
    - 35
    - 57
    - 73
    - 58
    - 62 
  n_row: 2
  n_col: 2
log_tag: 2tan_seq
ckpt_params:
  ckpt_dir: ckpt/2tan
  ckpt_freq: 0
  ref_fpath: './lh_ctx_mask.nii.gz'
num_epoch: 500